application: substratestack
version: 1
runtime: python
api_version: 1
skip_files: |
 (.*~)|
 (.*\.py[co])

handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /ace
  static_dir: ace-0.1.6-527-g8c45e96

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: index.py
